### ISSUE TITLE
App only loading a few, older photos. (v 1.3.6(1))

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#180] opened 2020-10-30 14:57 UTC
Looking at the North Fork Blackfoot (MT) there are only a few photos showing, they are the older ones. Is that intentional? 
Compare with the photos: https://www.americanwhitewater.org/content/River/view/?#/river-detail/986/gallery

**Comment by duffek** [comment] 2020-11-18 16:06
This is an issue I'm not sure about. I'm going to have to debug with @ryangroth5. The code I am sending out is asking for images tagged with specific properties, and i'm getting 5 images back. The Noli gorge is returning a ton of images but not the exact same ones as the website. We'll have to see what I need to tweak to get this to work as desired. It's probably more of a setting than a bug.

**Comment by duffek** [comment] 2021-01-18 17:49
duplicate of #187

**Closed by duffek** 2021-01-18 17:49 UTC
