### ISSUE TITLE
State list and river details not updating gages

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#147] opened 2019-12-24 15:27 UTC
I’ve checked out several gages are up to date on the gage graph, but not on the river list and river detail pages. Below is the NF French Broad. Little river is the same. 

![3DDA395F-0CCE-49BC-B0B5-E435F0B77B58](https://user-images.githubusercontent.com/7936679/71418299-d2358100-2637-11ea-9239-f84799851dc2.png)
![B35A6E80-DB65-428B-B5DC-A23E481FA55F](https://user-images.githubusercontent.com/7936679/71418300-d2358100-2637-11ea-9223-8ed8819b5c5e.png)
![2DD93ECD-A481-424A-90B2-EB0E47ADD530](https://user-images.githubusercontent.com/7936679/71418301-d2358100-2637-11ea-8090-856b66957d9b.png)
![DAD3FF34-AE50-4781-B57F-B8F7E17B2513](https://user-images.githubusercontent.com/7936679/71418302-d2358100-2637-11ea-842f-88ba6a7aceb5.png)

**Comment by riversandcreeks** [comment] 2019-12-24 17:24
I have noticed this same behavior. If I open a river page on the app and manually refresh it will populate the state listing correctly but you have to go one-by-one and refresh each one. Not intuitive.

**Comment by duffek** [comment] 2019-12-27 21:54
I’m not completely sure what is going on here. I’m not sure if I’m showing the wrong value or the values themselves are not updating like they should be. It looks like it’s not updating like it should be. I’m testing and comparing this against the website and will send out a quick fix once I am sure I have it working right since this is a resurfacing bug. The soonest Apple will start reviewing is on the 28th. I’m planning on having a fix for this ready to go for then.

**Comment by AWKevin** [comment] 2019-12-31 15:54
Was this issue fixed?

**Comment by duffek** [comment] 2020-01-02 17:07
I think I finally tracked this down. If you have a chance, please let me know if this works for you:

1. If you recently had the app open, please wait an hour or two before you open it again
2. Open the app and let the rivers list load
3. Click on a river and check if the values are incorrect
4. Go back to the runs list and pull down to refresh the values
5. Verify that all values should be up to date.

This is not the solution but a verification that it is working correctly when updating. The app should be auto-refreshing after 10 mins of inactivity. I've fixed this and I am sending out the fix today. If this was not the issue and the above does not work for you, then we have something else going on. 

I haven't been able to replicate this issue because I kept pulling down to refresh the values. I then realized it we my dev knowledge that was leading me astray! :)

**Comment by duffek** [comment] 2020-01-05 01:55
fixed in 1.3.1 live now

**Closed by duffek** 2020-01-05 01:55 UTC
Labels: bug

**Comment by riversandcreeks** [comment] 2020-01-05 16:36
Awesome! I can confirm it is working for me. Website and app gages are finally aligned. It's been months.

**Comment by duffek** [comment] 2020-01-05 17:00
@riversandcreeks Right on! Thanks for reviewing this. Your help is awesome and if you are in the Southeast I'll have to get you a pint sometime! Hopefully not a bootie beer...
