### ISSUE TITLE
Flows on App Not Updating

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#280] opened 2023-05-22 18:54 UTC
Flows on the iOS App are not updating, and with rising flows, that is dangerous. @ngottlieb can you look into this? It’s not good. Here is the river on which I noticed this last week:

![IMG_4080](https://github.com/AmericanWhitewater/aw-ios/assets/7936679/1feff2b3-d625-464b-a3bc-476c9f9f398c)
![IMG_4079](https://github.com/AmericanWhitewater/aw-ios/assets/7936679/8bd8d10b-9498-4aee-9ee2-0094a055a0db)
![IMG_4082](https://github.com/AmericanWhitewater/aw-ios/assets/7936679/084d9f4f-29c5-4df5-8156-7ae26802260d)
![IMG_4078](https://github.com/AmericanWhitewater/aw-ios/assets/7936679/b49d8205-4a33-46d3-8d12-320097d9fc9d)

**Comment by ngottlieb** [comment] 2023-05-23 19:13
@AWKevin can you confirm what I seemed to glean from the Slack conversation here -- that the issue is that the app just isn't refreshing the data? (meaning, does not refresh automatically when you open it, does not indicate refresh is needed, and only allows manual refresh on the reach list, not on reach details)

**Comment by AWKevin** [comment] 2023-05-23 19:28
Yes. If you go to the app, the flows are not updated. You have to click through to the AW site to see the real flows. 

The issue is about refreshing flow information. When you open the app it loads flows. Those are old. Then you have to slowly pull the screen down and release it just right to make it refresh. If you don't do that or do it wrong the old flows remain. Once you go to a river page refresh is not an option. I believe that the flows should be refreshed every time the app is opened or distance/region is changed. I also think there should be a better Refresh UI if it is not going to auto-refresh fairly often. 

 @Gregliest said he could maybe look at it next week, but I think it merits a quicker look given the sandbag potential.

**Comment by ngottlieb** [comment] 2023-05-23 19:31
OK, I'm looking at the iOS code and starting to understand what's going on here. What I'm hearing from you is:

- ensure that data is refreshed every time the app is opened or filters are changed

I'd also like to suggest that the timing you see on the reach detail view -- "May 14, 2023 8:04:39 PM" in your screenshot -- should reflect the time of the gauge reading, not just the timestamp of the last time the app was updated.

There's obviously a lot more that could be done here but these two things seems like the simplest and quickest path forward? @Gregliest input welcome...this is the first time I've attempted to work on an iOS app, let alone this particular one.

**Comment by AWKevin** [comment] 2023-05-23 19:36
I assume based on what I am seeing that both of your ideas would largely or entirely resolve the issue. Ensure refresh + timestamp the data. Note that right now the date stamp is wrong. It will say today's date but without updating the flow information.

**Comment by riversandcreeks** [comment] 2023-05-23 22:07
Yes to fixing this! I have seen these issues and encountered many boaters confused by our inconsistent flow data.

**Comment by ngottlieb** [comment] 2023-05-23 23:05
@AWKevin @riversandcreeks I have at least an initial fix for this that I think resolves the urgent aspects of the problem. Here's what I've done (pending code review, hopefully @Gregliest can take a quick look at it this week):

- added the ability to pull down and refresh the detail view
- changed the timestamp in the reach detail view to reflect last_gauge_updated from the API instead of the app-wide "last updated" -- note, this field has some mildly strange behavior, but it is at least consistent with what's displayed in the beta box on the website
- add "pull to refresh" call to action text when the last gauge reading is over an hour ago

Does that solve this problem at least for the purposes of this urgent bug fix, or is there more to it?

Notably, I have *not* adjusted the app to automatically reload anything at any time, though we could go that direction if desired.

**Comment by riversandcreeks** [comment] 2023-05-23 23:31
This makes sense to me as the first thing to try.

**Comment by AWKevin** [comment] 2023-05-24 13:11
Yes, let's do this asap. Thanks nick!

**Comment by Gregliest** [comment] 2023-05-25 18:48
Thanks for tackling this @ngottlieb. Your change looks good for the reach detail. However, I think there's a related bug on the main run list page, where sometimes the update timestamp is wrong. I'm looking into it now.

**Comment by AWKevin** [comment] 2023-07-20 13:36
Have the apps been updated with this fix?

**Comment by AWKevin** [comment] 2023-07-20 19:30
This does work, and is better, but is slow. Maybe a minute to update a river page. From a user standpoint I don't expect things to take that long. I just expect flows to be updated when I open the app. I'll close this and maybe we can improve it over time.

**Closed** 2023-07-20 19:30 UTC
