### ISSUE TITLE
App stuck on Loading River Data during travel

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#239] opened 2021-08-08 17:44 UTC
I just drove to PA, opened the app, reset my location (and tried just 15-50 miles) and filtered by distance and nothing I do will get any data to load. It’s been 20 hours and still no rivers…

**Comment by Gregliest** [comment] 2021-08-09 13:44
Can you share some more details? We can't debug based on the above. Did you try a region filter to see if reaches are loaded? I assume you checked your connection and that cellular data is enabled for the app?

**Comment by AWKevin** [comment] 2021-08-09 14:18
I think the app is getting stuck on a "Region" and that is what caused no rivers to load within 35 or whatever miles from my new location. I think it registered a North Carolina "region" even though I turned that off and filtered solely by distance, so the App could find no rivers within the distance sort and just kept trying. This morning things are different - I am not sure why. The reason I think this is right now I:

1. Open the app  and see rivers within 55 miles of me, but only in PA (I am on the border). 
2. I click on the slide bar icon in the upper right and see a Filter By Region blank screen and off-positioned slider 
3. To be sure I click the slider to turn on Filter By Region and ensure no states are selected. 
4. I unblock the slider, and click on the Distance tab. 
5. My location is correct, distance is correct, and I click done. 
6. I then see a list of rivers - only in PA, even though there are close rivers in MD. I click on Map at the bottom to confirm and see this: 

![IMG_AE69E0E5E558-1](https://user-images.githubusercontent.com/7936679/128721332-3a5b4c0d-e392-4a7c-968f-bc46a7494f85.jpeg)

**Comment by Gregliest** [comment] 2021-08-09 15:08
Hmmm, yeah there's definitely a bug here. I just got pins from New England (where I was a few days ago) and Oregon. I think @yeahphil 's work on refactoring the filters should help here. I can't repro anything unfortunately.

**Comment by AWKevin** [comment] 2021-08-09 15:45
In case it helps, every time I click on the little slide bar icon at the top to open the filter options it opens on Filter By Region, even though my last filter was by Distance. I think it used to open on whatever filter is currently in use (and maybe still is), which is my expected behavior. Distance and Region need to be exclusive, not overlapping selections, which now seems to be the case. Just some logic to ponder.

**Comment by Gregliest** [comment] 2021-08-12 20:54
I think this should be fixed by #243. I'm going to close for now, we can reopen if necessary.

**Comment by AWKevin** [comment] 2021-09-15 13:48
This happened again on my trip tot he galley this weekend. States work, distance does not.

**Comment by yeahphil** [comment] 2021-09-15 17:52
I think this is caused by #252 -- the app pre-bakes your distance to all the reaches it knows about and has to update that if you move. But that update isn't happening when it's supposed to, so when you filter by distance, you don't get the correct results.

**Comment by Gregliest** [comment] 2021-09-30 01:19
Let's try this again and see if it's fixed.

**Closed by Gregliest** 2021-09-30 01:19 UTC
Labels: next-release
